### ISSUE TITLE
Slider images don't load on launch

### ISSUE THREAD

**Issue by ffrutuoso** [vostpt/covid19-mobile#225]
[VIDEO HERE](https://www.dropbox.com/s/vj64f9yyvd53nfr/covid19app_slider.mp4?dl=0)

Slider images should be preloaded before user interaction.

**Comment by Vanethos** [comment]
We will have to load all the slides initially instead of creating them while we are sliding. Still, the first image may take some time to pop up

**Comment by ffrutuoso** [comment]
You can extended the splash page until the loading is done. I've included in the rive file a "standby" animation if needed.

This way, the image load would be hidden on start.

**Comment by Vanethos** [comment]
This won't work out-of the box, since usually network images are only loaded when needed, i.e., when we are viewing them in the page.

What could be better is to use an animation while we are loading the images.

Maybe a shimmer effect like the one presented here?

![https://raw.githubusercontent.com/hnvn/flutter_shimmer/master/screenshots/loading_list.gif](https://raw.githubusercontent.com/hnvn/flutter_shimmer/master/screenshots/loading_list.gif)

https://pub.dev/packages/shimmer

**Comment by ffrutuoso** [comment]
I'm ok with using this as a compromise, but I still think the slider images should be ready on first view. At least the first image should be loaded once the app opens.
